class_name LabArt
extends RefCounted

const BG = Color("0a131d")
const PANEL = Color("132331")
const LINE = Color("355064")
const TEXT = Color("eff8fa")
const MUTED = Color("9eb2c0")
const TEAL = Color("55edc7")
const AMBER = Color("ffc879")
const RED = Color("ff8179")
const BALLISTIC_WEAPONS = ["pistol","revolver","rifle","shotgun","sawed","nailgun","turret","flak","crossbow","rocket_gun","harpoon","cannon","minigun","grapple"]
const ENERGY_WEAPONS = ["railgun","flamer","freezer","tesla_gun","glue_gun","bouncer","pulse_gun","mine_gun","balloon_gun","vortex","disc_gun","taser","cluster","wind_gun"]
const MELEE_WEAPONS = ["sword","axe","spear","hammer","knife","katana","scythe","mace","chainsaw","bat","whip","plasma_blade","crowbar","halberd","hook"]
const EMITTER_COLORS = {
	"railgun":Color("70d9ff"), "flamer":Color("ffae55"), "freezer":Color("9cecff"),
	"tesla_gun":Color("9badff"), "glue_gun":Color("f5b874"), "bouncer":Color("ff8fa9"),
	"pulse_gun":Color("61ead4"), "mine_gun":Color("f49370"), "balloon_gun":Color("f9a2ce"),
	"vortex":Color("be97ff"), "disc_gun":Color("ffcf72"), "taser":Color("a8e7ff"),
	"cluster":Color("c1df78"), "wind_gun":Color("9adbcf"), "plasma_blade":Color("84edff")
}

static var _glow_texture: GradientTexture2D

static func soft_glow(c: CanvasItem, center: Vector2, radius: float, color: Color, strength: float = 1.0) -> void:
	# One cached radial gradient removes the visible concentric rings and
	# costs one draw command. The texture is generated by Godot at runtime.
	if _glow_texture==null:
		var gradient=Gradient.new()
		gradient.offsets=PackedFloat32Array([0.0,0.28,0.62,1.0])
		gradient.colors=PackedColorArray([Color(1,1,1,0.30),Color(1,1,1,0.15),Color(1,1,1,0.035),Color(1,1,1,0)])
		_glow_texture=GradientTexture2D.new()
		_glow_texture.gradient=gradient
		_glow_texture.width=128
		_glow_texture.height=128
		_glow_texture.fill=GradientTexture2D.FILL_RADIAL
		_glow_texture.fill_from=Vector2(0.5,0.5)
		_glow_texture.fill_to=Vector2(1.0,0.5)
	var extent=Vector2.ONE*radius*1.35
	c.draw_texture_rect(_glow_texture,Rect2(center-extent,extent*2.0),false,Color(color.r,color.g,color.b,color.a*strength))

static func glow_line(c: CanvasItem, from: Vector2, to: Vector2, color: Color, width: float = 2.0) -> void:
	c.draw_line(from,to,Color(color.r,color.g,color.b,0.06),width*6.0,true)
	c.draw_line(from,to,Color(color.r,color.g,color.b,0.16),width*3.0,true)
	c.draw_line(from,to,color,width,true)

static func bolt(c: CanvasItem, point: Vector2, radius: float = 2.0, color: Color = Color("c7d4d9")) -> void:
	c.draw_circle(point,radius+1,Color(0.02,0.04,0.05,0.55))
	c.draw_circle(point,radius,color)
	c.draw_line(point+Vector2(-radius*0.55,0),point+Vector2(radius*0.55,0),color.darkened(0.48),1,true)

static func bevel_box(c: CanvasItem, rect: Rect2, color: Color, radius: float = 5.0, border: Color = Color("8299a8"), depth: float = 3.0) -> void:
	box(c,Rect2(rect.position+Vector2(depth,depth+1),rect.size),Color(0.0,0.015,0.025,0.44),radius)
	LabSurface.plate(c,rect,color,radius,border,true)
	c.draw_line(rect.position+Vector2(radius,2),rect.position+Vector2(rect.size.x-radius,2),color.lightened(0.34),2,true)
	c.draw_line(rect.position+Vector2(rect.size.x-2,radius),rect.position+Vector2(rect.size.x-2,rect.size.y-radius),color.darkened(0.34),2,true)
	c.draw_line(rect.position+Vector2(radius,rect.size.y-2),rect.position+Vector2(rect.size.x-radius,rect.size.y-2),color.darkened(0.42),2,true)

static func weapon_finish(c: CanvasItem, kind: String, color: Color) -> void:
	var all_guns=BALLISTIC_WEAPONS+ENERGY_WEAPONS
	if kind in all_guns:
		var muzzle_x: Dictionary={"pistol":30,"revolver":28,"rifle":38,"shotgun":36,"sawed":26,"nailgun":44,"turret":34,"flak":32,"railgun":34,"crossbow":32,"rocket_gun":32,"flamer":38,"freezer":32,"tesla_gun":29,"harpoon":36,"glue_gun":21,"bouncer":26,"cannon":34,"minigun":31,"pulse_gun":30,"grapple":26,"mine_gun":27,"balloon_gun":27,"vortex":27,"disc_gun":28,"taser":24,"cluster":28,"wind_gun":26}
		var mx=float(muzzle_x.get(kind,30))
		# Receiver seam, raised sight, service screws and a proper muzzle crown.
		c.draw_line(Vector2(-14,-7),Vector2(10,-7),Color(0.82,0.93,0.96,0.24),1,true)
		c.draw_line(Vector2(-9,-10),Vector2(1,-10),Color("91a7b0"),2,true)
		c.draw_line(Vector2(-7,-11),Vector2(-7,-14),Color("a9bbc2"),1.5,true)
		for p in [Vector2(-11,-2),Vector2(5,-2)]: bolt(c,p,1.15,Color("b4c3c9"))
		c.draw_line(Vector2(mx,-4.5),Vector2(mx,4.5),Color("c4d1d6"),2,true)
		c.draw_circle(Vector2(mx,0),2.5,Color("101a20"))
		c.draw_circle(Vector2(mx,0),1.1,color.lightened(0.28))
		if kind in ENERGY_WEAPONS:
			soft_glow(c,Vector2(mx,0),10,Color(color.r,color.g,color.b,0.55),0.9)
			c.draw_arc(Vector2(mx-8,0),7,-1.05,1.05,12,color.lightened(0.22),2,true)
			c.draw_circle(Vector2(mx-8,0),2,Color("e8ffff"))
		else:
			c.draw_line(Vector2(mx-5,-5),Vector2(mx-1,-8),Color("71858e"),2,true)
		# Layered grip wrap remains readable even at catalog scale.
		if kind in ["pistol","revolver","nailgun","flak","glue_gun"]:
			for y in range(9,18,3): c.draw_line(Vector2(-8,y),Vector2(1,y+1),Color(0.75,0.88,0.9,0.18),1,true)

static func box(c: CanvasItem, rect: Rect2, color: Color, radius: float = 6.0, border: Color = Color.TRANSPARENT) -> void:
	var style = StyleBoxFlat.new()
	style.bg_color = color
	style.set_corner_radius_all(int(radius))
	if border.a > 0:
		style.set_border_width_all(1)
		style.border_color = border
	c.draw_style_box(style, rect)
	# A restrained bevel catches the key light and keeps procedural props from
	# looking like flat vector stickers.
	if rect.size.x>12 and rect.size.y>8 and color.a>0.15:
		var inset=minf(maxf(radius,2.0),rect.size.x*0.2)
		c.draw_line(rect.position+Vector2(inset,1),rect.position+Vector2(rect.size.x-inset,1),Color(1,1,1,0.075*color.a),1,true)

static func _hex(at: Vector2, radius: float) -> PackedVector2Array:
	var pts=PackedVector2Array()
	for i in range(6): pts.append(at+Vector2.from_angle(float(i)*TAU/6.0-PI/2.0)*radius)
	return pts

static func grip(c: CanvasItem, from: Vector2, to: Vector2, width: float, color: Color = Color("71503c")) -> void:
	LabSurface.line(c,from,to,Color("182932"),width+2.0)
	LabSurface.line(c,from,to,color,width)
	var axis=(to-from).normalized()
	var cross=axis.orthogonal()*width*0.45
	for i in range(1,6):
		var p=from.lerp(to,float(i)/6.0)
		c.draw_line(p-cross-axis,p+cross+axis,color.darkened(0.48),1.1,true)
	LabSurface.line(c,from-cross,from+cross,Color("adc1ca"),2.8)
	LabSurface.line(c,to-cross,to+cross,Color("adc1ca"),2.2)

static func vents(c: CanvasItem, rect: Rect2, count: int = 4) -> void:
	for i in range(count):
		var x=rect.position.x+(float(i)+0.5)*rect.size.x/float(count)
		c.draw_line(Vector2(x,rect.position.y),Vector2(x-1,rect.end.y),Color("162833"),1.7,true)
		c.draw_line(Vector2(x+1,rect.position.y),Vector2(x,rect.end.y),Color(0.8,0.94,1,0.2),0.65,true)

static func blade(c: CanvasItem, outline: PackedVector2Array, spine: PackedVector2Array, color: Color = Color("c3d6e0")) -> void:
	LabSurface.polygon(c,outline,color)
	c.draw_polyline(spine,Color("f2fbff"),1.2,true)
	var edge=outline.duplicate()
	edge.append(outline[0])
	c.draw_polyline(edge,Color("e0f0f6"),0.65,true)

static func wear_noise(i: int) -> float:
	var v=sin(float(i)*91.7+float(i%23)*37.3)*23421.631
	return v-floorf(v)

static func damage(c: CanvasItem, rect: Rect2, wear: float, seed_value: int) -> void:
	# Progressive battle damage on a single plate: scuffs first, then dents,
	# then torn plating with the loom showing through. Deterministic per part,
	# so a robot keeps the same scars instead of shimmering as it is redrawn.
	if wear<=0.10: return
	for i in range(int(clampf(wear*8.0,1,8))):
		var from=rect.position+Vector2(rect.size.x*wear_noise(seed_value*7+i*13),rect.size.y*wear_noise(seed_value*11+i*17))
		var to=from+Vector2(3.0+wear_noise(seed_value+i*5)*6.0,-2.0+wear_noise(seed_value*3+i*7)*5.0)
		c.draw_line(from,to,Color(0.04,0.08,0.11,0.22+wear*0.34),1.0+wear,true)
	if wear>0.30:
		for i in range(int(clampf((wear-0.30)*7.0,1,3))):
			var at=rect.position+Vector2(rect.size.x*wear_noise(seed_value*19+i*29),rect.size.y*wear_noise(seed_value*23+i*31))
			var radius=2.0+wear*3.2
			c.draw_circle(at,radius,Color(0.16,0.24,0.30,0.38))
			c.draw_arc(at,radius,0.7,2.5,8,Color(1,1,1,0.28),1,true)
	if wear>0.55:
		# Placed by seed: a fixed fraction put an identical hole in every limb.
		var tear=Rect2(rect.position+rect.size*Vector2(0.12+wear_noise(seed_value*37)*0.34,0.16+wear_noise(seed_value*41)*0.44),rect.size*Vector2(0.42,0.26))
		c.draw_rect(tear,Color(0.14,0.22,0.28,0.65))
		c.draw_line(tear.position+Vector2(1,tear.size.y*0.42),tear.end-Vector2(1,tear.size.y*0.5),Color("c4703a"),1.5,true)
		c.draw_line(tear.position+Vector2(1,tear.size.y*0.74),tear.end-Vector2(1,tear.size.y*0.18),Color("3f9f74"),1.5,true)
		c.draw_polyline(PackedVector2Array([tear.position,tear.position+Vector2(tear.size.x*0.3,-2.5),tear.position+Vector2(tear.size.x*0.6,1.5),tear.position+Vector2(tear.size.x,-1.5)]),Color(0.55,0.62,0.66,0.5),1.5,true)
	if wear>0.80:
		# Live arcing across the worst breach.
		var arc_at=rect.position+rect.size*0.5
		c.draw_polyline(PackedVector2Array([arc_at+Vector2(-5,-3),arc_at+Vector2(-1,0),arc_at+Vector2(-3,2),arc_at+Vector2(4,5)]),Color(1.0,0.85,0.45,0.75),1.5,true)
		soft_glow(c,arc_at,7,Color(1.0,0.7,0.3,0.5),0.7)

static func icon(c: CanvasItem, kind: String, center: Vector2, scale_value: float = 1.0, color: Color = TEAL, rot: float = 0.0) -> void:
	if color==TEAL and EMITTER_COLORS.has(kind): color=EMITTER_COLORS[kind]
	if kind in LabVehicle.KINDS:
		LabVehicle.draw_icon(c,kind,center,scale_value,rot)
		return
	if kind in LabParts.KINDS:
		LabParts.draw_icon(c,kind,center,scale_value,rot)
		return
	if kind.begins_with("virus_"):
		var vc={"virus_rage":Color("ef6f62"),"virus_dance":Color("ff82ad"),"virus_panic":Color("ffcc55"),"virus_guard":Color("5da8ff"),"virus_leap":Color("a7e05c"),"virus_orbit":Color("b278e8"),"virus_float":Color("df7cf2"),"virus_hunter":Color("54d9ff"),"virus_follow":Color("65e39a"),"virus_spin":Color("4ce0bd")}.get(kind,color)
		c.draw_set_transform(center,rot,Vector2.ONE*scale_value)
		for side in [-1,1]:
			for pin in [-9,-3,3,9]:
				LabSurface.plate(c,Rect2(side*17-2,pin-1.4,4,2.8),Color("c8a766"),0.6)
				LabSurface.plate(c,Rect2(pin-1.4,side*17-2,2.8,4),Color("c8a766"),0.6)
		LabSurface.plate(c,Rect2(-16,-16,32,32),Color("2a4d46"),5,vc)
		LabSurface.plate(c,Rect2(-11,-11,22,22),Color("182b32"),3,Color("6c9f91"))
		for side in [-1,1]:
			c.draw_polyline(PackedVector2Array([Vector2(side*14,-10),Vector2(side*14,8),Vector2(side*10,13)]),Color("b1a26b"),0.8,true)
			bolt(c,Vector2(side*12,-12),1.0,Color("c9dbc4"))
		match kind:
			"virus_rage":
				LabSurface.polygon(c,PackedVector2Array([Vector2(0,-8),Vector2(8,6),Vector2(-8,6)]),vc)
			"virus_dance":
				LabSurface.circle(c,Vector2(-5,-2),3,vc); LabSurface.circle(c,Vector2(5,4),3,vc)
			"virus_panic":
				c.draw_polyline(PackedVector2Array([Vector2(-8,6),Vector2(-3,-6),Vector2(2,6),Vector2(8,-6)]),vc,2)
			"virus_guard":
				LabSurface.rect(c,Rect2(-6,-7,12,14),vc,false,2)
			"virus_leap":
				LabSurface.line(c,Vector2(0,8),Vector2(0,-8),vc,3); LabSurface.line(c,Vector2(-6,-2),Vector2(0,-8),vc,3); LabSurface.line(c,Vector2(6,-2),Vector2(0,-8),vc,3)
			"virus_orbit":
				c.draw_arc(Vector2.ZERO,9,0,4.2,16,vc,2,true); LabSurface.circle(c,Vector2(8,-4),3,vc)
			"virus_float":
				LabSurface.circle(c,Vector2(0,-4),4,vc); LabSurface.line(c,Vector2(-6,6),Vector2(6,6),vc,2)
			"virus_hunter":
				LabSurface.polygon(c,PackedVector2Array([Vector2(-8,-6),Vector2(8,0),Vector2(-8,6)]),vc)
			"virus_follow":
				LabSurface.circle(c,Vector2(-5,0),4,vc); LabSurface.circle(c,Vector2(6,0),3,vc)
			"virus_spin":
				c.draw_arc(Vector2.ZERO,8,-0.4,4.8,16,vc,2,true)
		c.draw_set_transform(Vector2.ZERO)
		return
	if kind.begins_with("robot_"):
		var colors={"robot_scout":Color("54d9ff"),"robot_titan":Color("d99b55"),"robot_jumper":Color("a7e05c"),"robot_magnet":Color("b278e8"),"robot_tesla":Color("5da8ff"),"robot_bomber":Color("ef6f62"),"robot_medic":Color("65e39a"),"robot_antigrav":Color("df7cf2"),"robot_runner":Color("ffcc55"),"robot_acrobat":Color("ff82ad")}
		var variant_color: Color=colors.get(kind,color)
		icon(c,"robot",center,scale_value,variant_color,rot)
		c.draw_set_transform(center,rot,Vector2.ONE*scale_value)
		match kind:
			"robot_scout":
				LabSurface.line(c,Vector2(-9,-25),Vector2(-15,-33),variant_color,2)
				LabSurface.circle(c,Vector2(-16,-34),2,AMBER)
			"robot_titan":
				LabSurface.rect(c,Rect2(-17,-23,34,48),variant_color,false,4)
				LabSurface.line(c,Vector2(-18,-2),Vector2(-25,15),variant_color,6)
				LabSurface.line(c,Vector2(18,-2),Vector2(25,15),variant_color,6)
			"robot_jumper":
				for x in [-8,8]: c.draw_polyline(PackedVector2Array([Vector2(x,28),Vector2(x-3,32),Vector2(x+3,35),Vector2(x,39)]),variant_color,2)
			"robot_magnet":
				c.draw_arc(Vector2(0,12),7,0,PI,14,variant_color,3,true)
			"robot_tesla":
				c.draw_polyline(PackedVector2Array([Vector2(-2,5),Vector2(5,5),Vector2(0,13),Vector2(6,13),Vector2(-4,23),Vector2(-1,15),Vector2(-7,15)]),AMBER,2)
			"robot_bomber":
				LabSurface.circle(c,Vector2(0,12),7,RED)
				LabSurface.line(c,Vector2(0,8),Vector2(0,14),TEXT,2)
				LabSurface.circle(c,Vector2(0,17),1,TEXT)
			"robot_medic":
				LabSurface.rect(c,Rect2(-2,5,4,15),TEXT)
				LabSurface.rect(c,Rect2(-7,10,14,5),TEXT)
			"robot_antigrav":
				LabSurface.line(c,Vector2(-8,31),Vector2(0,23),variant_color,3)
				LabSurface.line(c,Vector2(0,23),Vector2(8,31),variant_color,3)
			"robot_runner":
				LabSurface.line(c,Vector2(-20,8),Vector2(-29,8),variant_color,3)
				LabSurface.line(c,Vector2(-18,15),Vector2(-25,15),variant_color,2)
			"robot_acrobat":
				c.draw_arc(Vector2.ZERO,32,-2.2,-0.4,16,variant_color,2,true)
				LabSurface.polygon(c,PackedVector2Array([Vector2(25,-14),Vector2(18,-15),Vector2(22,-8)]),variant_color)
		c.draw_set_transform(Vector2.ZERO)
		return
	var artwork_scale=Vector2.ONE*scale_value
	if c is LabBody and LabGeometry.FRAMES.has(kind):
		var authored=LabGeometry.frame(kind)
		artwork_scale=c.dimensions/authored.size
		center-=authored.get_center()*artwork_scale
	c.draw_set_transform(center, rot, artwork_scale)
	# Catalog tiles render at roughly half scale, where fine detail turns to
	# mush; the in-world body gets the extra passes.
	var fine=scale_value>=0.8
	match kind:
		"robot":
			# Compact three-quarter mechanical silhouette for catalog cards.
			LabSurface.line(c,Vector2(0,-25),Vector2(0,-20),Color("8097a1"),2)
			soft_glow(c,Vector2(0,-28),7,Color(color.r,color.g,color.b,0.5),0.8)
			LabSurface.circle(c,Vector2(0,-28),3.2,AMBER)
			for x in [-15,15]:
				LabSurface.plate(c,Rect2(x-2,-15,4,8),Color("6e858f"),2)
			bevel_box(c,Rect2(-14,-22,28,21),Color("d9e6e9"),7,Color("78909a"),2)
			LabSurface.plate(c,Rect2(-11,-16,22,9),Color("102832"),4,Color("36505b"))
			for x in [-6,6]:
				LabSurface.circle(c,Vector2(x,-11.5),2.2,Color("06151c"))
				LabSurface.circle(c,Vector2(x,-12),1.35,color)
			LabSurface.rect(c,Rect2(-5,-1,10,5),Color("627985"))
			LabSurface.polygon(c,PackedVector2Array([Vector2(-11,3),Vector2(11,3),Vector2(9,24),Vector2(-9,24)]),color.darkened(0.08))
			c.draw_polyline(PackedVector2Array([Vector2(-11,3),Vector2(11,3),Vector2(9,24),Vector2(-9,24),Vector2(-11,3)]),Color("8aa0ad"),1.5,true)
			LabSurface.plate(c,Rect2(-6,8,12,10),Color("173039"),3)
			LabSurface.circle(c,Vector2(0,13),3.5,color.lightened(0.28))
			for s in [-1,1]:
				LabSurface.circle(c,Vector2(s*13,7),4.2,Color("607681"))
				LabSurface.circle(c,Vector2(s*13,7),2.2,TEXT)
				LabSurface.line(c,Vector2(s*14,9),Vector2(s*18,23),Color("d7e4e7"),5,true)
				LabSurface.circle(c,Vector2(s*18,24),3,Color("647b86"))
				LabSurface.line(c,Vector2(s*6,25),Vector2(s*8,36),Color("d7e4e7"),6,true)
				LabSurface.line(c,Vector2(s*8,36),Vector2(s*12,36),Color("91a9b2"),3,true)
		"crate":
			bevel_box(c,Rect2(-22,-22,44,44),Color("8d603d"),4,Color("d8a25f"),3)
			# Recessed boards, diagonal brace, grain and fasteners.
			LabSurface.plate(c,Rect2(-17,-17,34,34),Color("70472f"),2,Color("b77a49"))
			for x in [-12,0,12]: LabSurface.line(c,Vector2(x,-17),Vector2(x,17),Color("a66f43"),3)
			LabSurface.line(c,Vector2(-16,15),Vector2(15,-16),Color("d3a062"),7,true)
			LabSurface.line(c,Vector2(-15,13),Vector2(14,-16),Color("f0c17c"),1.4,true)
			for y in [-10,7]: LabSurface.line(c,Vector2(-9,y),Vector2(-2,y-2),Color(0.2,0.11,0.06,0.34),1)
			for p in [Vector2(-17,-17),Vector2(17,-17),Vector2(-17,17),Vector2(17,17)]: bolt(c,p,1.4,Color("d7aa70"))
		"barrel":
			bevel_box(c,Rect2(-18,-27,36,54),Color("964a3d"),8,Color("d88959"),3)
			LabSurface.plate(c,Rect2(-14,-23,7,46),Color(1,0.63,0.36,0.13),3)
			for y in [-17,17]:
				LabSurface.line(c,Vector2(-19,y),Vector2(19,y),Color("e4a268"),5,true)
				LabSurface.line(c,Vector2(-16,y-1),Vector2(16,y-1),Color("ffd096"),1,true)
			c.draw_arc(Vector2(0,-21),15,3.35,6.08,18,Color(1,0.72,0.46,0.35),2,true)
			LabSurface.polygon(c,PackedVector2Array([Vector2(0,-10),Vector2(10,8),Vector2(-10,8)]),AMBER)
			LabSurface.line(c,Vector2(0,-4),Vector2(0,2),BG,3)
			LabSurface.circle(c,Vector2(0,5),1.5,BG)
		"ball":
			soft_glow(c,Vector2.ZERO,25,Color(0.4,0.75,0.95,0.18),0.5)
			LabSurface.circle(c,Vector2(3,4),23,Color(0,0,0,0.28))
			LabSurface.circle(c,Vector2.ZERO,22,Color("354e67"))
			LabSurface.circle(c,Vector2(-4,-5),16,Color("4d6d88"))
			LabSurface.circle(c,Vector2(-8,-9),7,Color(0.72,0.88,0.96,0.24))
			c.draw_arc(Vector2.ZERO,21,0,TAU,48,Color("9eb7c8"),2,true)
			c.draw_arc(Vector2(-3,-4),14,3.45,5.25,20,Color("d5e8ef"),2.5,true)
			LabSurface.circle(c,Vector2(7,8),4.5,Color("223746"))
			bolt(c,Vector2(7,8),1.5,Color("819aaa"))
		"plank":
			bevel_box(c,Rect2(-30,-8,60,16),Color("94663e"),3,Color("d4a466"),2)
			LabSurface.line(c,Vector2(-25,-3),Vector2(24,-3),Color("dfb276"),2,true)
			LabSurface.line(c,Vector2(-19,3),Vector2(8,2),Color(0.22,0.12,0.06,0.42),1)
			LabSurface.line(c,Vector2(12,3),Vector2(23,1),Color(0.22,0.12,0.06,0.32),1)
			for x in [-24,24]: bolt(c,Vector2(x,3),1.5,Color("6f7b7c"))
		"metal":
			bevel_box(c,Rect2(-25,-19,50,38),Color("344a5c"),5,Color("91aabd"),3)
			LabSurface.plate(c,Rect2(-20,-14,40,28),Color("2d4151"),2,Color("526c7e"))
			LabSurface.line(c,Vector2(-17,11),Vector2(17,-11),Color("70899b"),7,true)
			LabSurface.line(c,Vector2(-15,8),Vector2(15,-11),Color("adc0ca"),1.5,true)
			for x in [-18,18]:
				for y in [-12,12]: bolt(c,Vector2(x,y),1.7,TEXT)
		"thruster":
			LabSurface.polygon(c,PackedVector2Array([Vector2(-8,-25),Vector2(8,-25),Vector2(13,-18),Vector2(13,10),Vector2(8,17),Vector2(-8,17),Vector2(-13,10),Vector2(-13,-18)]),Color("bdd3dc"))
			LabSurface.plate(c,Rect2(-8,-16,16,16),Color("2c4758"),3)
			LabSurface.circle(c,Vector2(0,-8),4.5,color)
			vents(c,Rect2(-8,4,16,7),4)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-9,14),Vector2(9,14),Vector2(14,22),Vector2(-14,22)]),Color("687f90"))
			LabSurface.plate(c,Rect2(-10,19,20,4),Color("213846"),1)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-7,24),Vector2(0,38),Vector2(7,24)]),AMBER)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-3,24),Vector2(0,32),Vector2(3,24)]),Color("fff4c6"))
		"mine":
			LabSurface.ellipse(c,Vector2(0,5),Vector2(25,9),Color("394c5e"))
			LabSurface.polygon(c,PackedVector2Array([Vector2(-24,5),Vector2(-18,-4),Vector2(-9,-8),Vector2(9,-8),Vector2(18,-4),Vector2(24,5)]),Color("7f939f"))
			LabSurface.ellipse(c,Vector2(0,-5),Vector2(12,5),Color("455d6d"))
			LabSurface.ellipse(c,Vector2(0,-8),Vector2(6,3),RED)
			for x in [-17,17]: bolt(c,Vector2(x,3),1.8,Color("b6cbd5"))
			for x in [-10,0,10]: LabSurface.line(c,Vector2(x-2,7),Vector2(x+2,7),AMBER,1.4)
		"magnet":
			var horseshoe=PackedVector2Array([Vector2(-24,18),Vector2(-24,-8),Vector2(-19,-19),Vector2(-9,-24),Vector2(9,-24),Vector2(19,-19),Vector2(24,-8),Vector2(24,18),Vector2(13,18),Vector2(13,-7),Vector2(9,-13),Vector2(-9,-13),Vector2(-13,-7),Vector2(-13,18)])
			LabSurface.polygon(c,horseshoe,Color("a1b7c2"))
			LabSurface.plate(c,Rect2(-24,0,11,18),Color("d85f59"),2)
			LabSurface.plate(c,Rect2(13,0,11,18),Color("569fda"),2)
			for x in [-24,13]:
				LabSurface.plate(c,Rect2(x,13,11,5),Color("e2ecef"),1)
				bolt(c,Vector2(x+5.5,5),1.6)
			c.draw_arc(Vector2(0,-3),17,PI,TAU,28,Color("f0f8fa"),1.4,true)
		"fan":
			LabSurface.plate(c,Rect2(-24,-25,48,50),Color("597382"),5,Color("b5cbd5"))
			LabSurface.recess(c,Vector2.ZERO,20,Color("537484"))
			for i in range(5):
				var a=float(i)*TAU/5.0
				LabSurface.polygon(c,PackedVector2Array([Vector2.from_angle(a)*4,Vector2.from_angle(a+0.15)*17,Vector2.from_angle(a+0.8)*18,Vector2.from_angle(a+1.1)*9]),color.darkened(0.12))
			for radius in [11,18]: c.draw_arc(Vector2.ZERO,radius,0,TAU,48,Color(0.69,0.81,0.88,0.3),0.8,true)
			LabSurface.circle(c,Vector2.ZERO,5,Color("c3d6dd"))
			for x in [-19,19]:
				for y in [-20,20]: bolt(c,Vector2(x,y),1.7)
		"coil":
			LabSurface.plate(c,Rect2(-20,15,40,13),Color("3b4d5d"),3)
			LabSurface.line(c,Vector2(0,15),Vector2(0,-19),Color("b9cbd1"),5)
			for y in [-12,-4,4,12]: c.draw_arc(Vector2(0,y),12,0,TAU,20,Color("b06f4e"),3,true)
			LabSurface.circle(c,Vector2(0,-24),7,color)
			c.draw_arc(Vector2(0,-24),11,-2.7,-0.3,12,Color("9fe8ff"),2,true)
		"sticky":
			LabSurface.plate(c,Rect2(-14,-9,28,18),Color("59626b"),6,Color("aeb8bd"))
			for x in [-9,9]: LabSurface.circle(c,Vector2(x,0),3,Color("242e35"))
			LabSurface.circle(c,Vector2(0,-3),4,RED)
			LabSurface.line(c,Vector2(0,-9),Vector2(7,-17),AMBER,2)
		"glass":
			LabSurface.plate(c,Rect2(-34,-7,68,14),Color(0.45,0.9,1,0.22),2,Color("8be5ef"))
			LabSurface.line(c,Vector2(-29,3),Vector2(-4,-3),Color(0.85,1,1,0.65),2)
			LabSurface.line(c,Vector2(4,3),Vector2(25,-2),Color(0.85,1,1,0.4),1)
		"trampoline":
			LabSurface.plate(c,Rect2(-36,-8,72,7),Color("4a6778"),2,Color("9bbbc8"))
			LabSurface.plate(c,Rect2(-29,-7,58,5),color.darkened(0.20),2)
			for x in [-29,29]:
				LabSurface.line(c,Vector2(x,-1),Vector2(x,12),Color("3a5260"),5)
				for i in range(3): c.draw_line(Vector2(x-4,1+i*3),Vector2(x+4,3+i*3),Color("b6d1dc"),1.6,true)
				LabSurface.plate(c,Rect2(x-7,12,14,4),Color("829ca9"),1)
			LabSurface.line(c,Vector2(-24,-5),Vector2(24,-5),color.lightened(0.25),1.3)
		"bumper":
			LabSurface.circle(c,Vector2.ZERO,23,Color("334b5c"))
			c.draw_arc(Vector2.ZERO,22,0,TAU,36,color,6,true)
			LabSurface.circle(c,Vector2.ZERO,10,AMBER)
			for i in range(8): LabSurface.circle(c,Vector2.from_angle(i*TAU/8)*17,2,TEXT)
		"weight":
			LabSurface.plate(c,Rect2(-24,-18,48,39),Color("303b46"),5,Color("8797a0"))
			c.draw_arc(Vector2(0,-18),12,PI,TAU,18,Color("8797a0"),5,true)
			c.draw_string(ThemeDB.fallback_font,Vector2(-12,10),"50",HORIZONTAL_ALIGNMENT_CENTER,24,13,TEXT)
		"balloon":
			LabSurface.circle(c,Vector2(0,-7),18,Color("e06f72"))
			c.draw_arc(Vector2(-5,-12),9,3.4,5.0,12,Color(1,1,1,0.5),3,true)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-4,10),Vector2(4,10),Vector2(0,17)]),Color("e06f72"))
			LabSurface.line(c,Vector2(0,17),Vector2(0,34),Color("b4c8cc"),1)
		"wheel":
			LabSurface.circle(c,Vector2.ZERO,26,Color("222d36"))
			c.draw_arc(Vector2.ZERO,25,0,TAU,40,Color("758994"),5,true)
			for i in range(8): LabSurface.line(c,Vector2.from_angle(i*TAU/8)*7,Vector2.from_angle(i*TAU/8)*20,color,3)
			LabSurface.circle(c,Vector2.ZERO,8,AMBER)
		"syringe_life","syringe_acid","syringe_nitro","syringe_overclock","syringe_freeze":
			var fluid_col = Color("4ce0bd")
			match kind:
				"syringe_acid": fluid_col = Color("4ade80")
				"syringe_nitro": fluid_col = AMBER
				"syringe_overclock": fluid_col = Color("38bdf8")
				"syringe_freeze": fluid_col = Color("a5f3fc")
			bevel_box(c, Rect2(-6, -14, 12, 24), Color(0.8, 0.95, 1.0, 0.25), 3, Color(0.7, 0.9, 1.0, 0.8), 1.5)
			LabSurface.plate(c, Rect2(-4, -8, 8, 16), fluid_col, 2)
			soft_glow(c, Vector2(0, 0), 10, Color(fluid_col.r, fluid_col.g, fluid_col.b, 0.5), 0.7)
			for y in [-4, 0, 4]: LabSurface.line(c,Vector2(-4, y), Vector2(-1, y), Color(1, 1, 1, 0.7), 1)
			LabSurface.line(c,Vector2(0, -14), Vector2(0, -22), Color("94a3b8"), 2)
			LabSurface.line(c,Vector2(-5, -22), Vector2(5, -22), Color("cbd5e1"), 2)
			LabSurface.line(c,Vector2(0, 10), Vector2(0, 20), Color("e2e8f0"), 1.8)
			LabSurface.circle(c,Vector2(0, 20), 0.8, Color(1, 1, 1, 0.9))
		"c4":
			bevel_box(c, Rect2(-16, -10, 32, 20), Color("4b5563"), 4, Color("6b7280"), 2)
			LabSurface.line(c,Vector2(-12, -4), Vector2(12, -4), Color("eab308"), 3, true)
			LabSurface.plate(c, Rect2(-8, 1, 16, 7), Color("1f2937"), 2)
			LabSurface.circle(c,Vector2(5, 4), 2.0, RED)
			soft_glow(c, Vector2(5, 4), 6, Color(1, 0.2, 0.2, 0.7), 0.8)
			LabSurface.line(c,Vector2(-10, -10), Vector2(-12, -18), Color("9ca3af"), 1.5)
			LabSurface.circle(c,Vector2(-12, -18), 1.5, AMBER)
		"laser_cutter":
			bevel_box(c, Rect2(-22, -12, 44, 24), Color("374151"), 4, Color("9ca3af"), 2)
			for x in [-12, -6, 0]:
				LabSurface.line(c,Vector2(x, -10), Vector2(x, 10), Color("1f2937"), 2)
			LabSurface.plate(c, Rect2(14, -8, 8, 16), Color("dc2626"), 3, Color("f87171"))
			LabSurface.circle(c,Vector2(18, 0), 3.5, Color("fef08a"))
			soft_glow(c, Vector2(18, 0), 12, Color(1, 0.3, 0.2, 0.8), 0.9)
		"singularity":
			LabSurface.circle(c,Vector2.ZERO, 17, Color("09090b"))
			c.draw_arc(Vector2.ZERO, 16, 0, TAU, 32, Color("7c3aed"), 3, true)
			c.draw_arc(Vector2.ZERO, 12, 0, TAU, 24, Color("c084fc"), 2, true)
			LabSurface.circle(c,Vector2.ZERO, 6, Color("f3e8ff"))
			soft_glow(c, Vector2.ZERO, 22, Color(0.6, 0.2, 1.0, 0.6), 0.85)
		"pistol":
			LabSurface.polygon(c,PackedVector2Array([Vector2(-14,1),Vector2(8,1),Vector2(7,7),Vector2(1,8),Vector2(-2,21),Vector2(-13,19),Vector2(-9,6),Vector2(-16,6)]),Color("3d5260"))
			LabSurface.plate(c,Rect2(-20,-9,42,12),Color("77919e"),3,Color("bad0d8"))
			LabSurface.plate(c,Rect2(20,-6,10,7),Color("435b69"),1)
			vents(c,Rect2(-17,-7,10,7),4)
			LabSurface.plate(c,Rect2(3,-6,10,4),Color("263e4b"),1)
			c.draw_arc(Vector2(3,7),6,0,PI,16,Color("97adba"),1.8,true)
			LabSurface.line(c,Vector2(0,4),Vector2(1,8),Color("b8cbd4"),1.4)
		"revolver":
			bevel_box(c,Rect2(-12,4,13,16),Color("49362d"),3,Color("8e6a4c"),2)
			bevel_box(c,Rect2(-16,-8,26,14),Color("627783"),3,Color("b8c7cc"),2)
			LabSurface.circle(c,Vector2(-2,1),9,Color("4a5c68"))
			c.draw_arc(Vector2(-2,1),8,0,TAU,20,Color("a8b8c2"),2,true)
			for i in range(6): LabSurface.circle(c,Vector2(-2,1)+Vector2.from_angle(i*TAU/6.0)*4.6,1.7,Color("222d36"))
			LabSurface.plate(c,Rect2(6,-5,22,8),Color("4a5c68"),2)
			LabSurface.line(c,Vector2(-12,-8),Vector2(-17,-14),TEXT,2)
			LabSurface.circle(c,Vector2(28,-1),3,color)
			LabSurface.circle(c,Vector2(28,-1),1.5,AMBER)
		"rifle":
			LabSurface.polygon(c,PackedVector2Array([Vector2(-39,-5),Vector2(-23,-5),Vector2(-16,2),Vector2(-25,7),Vector2(-37,14),Vector2(-41,12)]),Color("476170"))
			LabSurface.plate(c,Rect2(-23,-8,36,14),Color("6b8494"),3,Color("afc8d4"))
			LabSurface.plate(c,Rect2(12,-5,26,7),Color("334d5e"),1)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-1,5),Vector2(9,5),Vector2(7,19),Vector2(2,22),Vector2(-5,19)]),Color("435b69"))
			grip(c,Vector2(-14,6),Vector2(-17,17),6,Color("2d424f"))
			vents(c,Rect2(11,-5,19,6),5)
			c.draw_arc(Vector2(-8,7),5,0.0,PI,12,Color("9eb4c1"),1.4,true)
			LabSurface.line(c,Vector2(-37,-3),Vector2(-26,-3),Color("a5bdc8"),1.4)
		"shotgun":
			LabSurface.polygon(c,PackedVector2Array([Vector2(-37,-4),Vector2(-23,-4),Vector2(-12,1),Vector2(-21,7),Vector2(-31,15),Vector2(-38,12)]),Color("ad7d46"))
			LabSurface.plate(c,Rect2(-23,-9,27,15),Color("546c7c"),3,Color("9eb6c4"))
			LabSurface.plate(c,Rect2(1,-6,35,6),Color("567181"),2)
			LabSurface.plate(c,Rect2(2,1,31,5),Color("2c434f"),2)
			grip(c,Vector2(7,4),Vector2(23,4),9,Color("b58448"))
			c.draw_arc(Vector2(-9,7),6,0.0,PI,14,Color("b8c7cd"),1.6,true)
			LabSurface.line(c,Vector2(-37,-2),Vector2(-37,12),Color("273946"),3)
		"sawed":
			LabSurface.polygon(c,PackedVector2Array([Vector2(-21,-1),Vector2(-8,-1),Vector2(-5,5),Vector2(-16,17),Vector2(-25,14),Vector2(-19,5)]),Color("96683f"))
			LabSurface.plate(c,Rect2(-15,-10,24,19),Color("7c8990"),4,Color("becad0"))
			LabSurface.plate(c,Rect2(5,-10,21,8),Color("465f70"),2)
			LabSurface.plate(c,Rect2(5,1,21,8),Color("465f70"),2)
			for y in [-6,5]:
				LabSurface.ellipse(c,Vector2(26,y),Vector2(2.5,4),Color("1c303b"))
				c.draw_line(Vector2(8,y-2),Vector2(23,y-2),Color("a5c1d1"),1,true)
			c.draw_arc(Vector2(-5,9),5,0,PI,12,Color("a7b6bd"),1.4,true)
		"nailgun":
			grip(c,Vector2(-10,3),Vector2(-10,19),9,Color("31444e"))
			LabSurface.polygon(c,PackedVector2Array([Vector2(-22,-8),Vector2(-17,-14),Vector2(5,-14),Vector2(13,-8),Vector2(13,8),Vector2(-18,8),Vector2(-22,3)]),Color("d99b3f"))
			LabSurface.plate(c,Rect2(10,-6,21,9),Color("637f90"),2)
			LabSurface.plate(c,Rect2(-1,7,11,15),Color("6a7f8e"),2)
			vents(c,Rect2(-15,-10,15,8),4)
			LabSurface.line(c,Vector2(29,-2),Vector2(42,-2),Color("bfd2dc"),2.5)
			LabSurface.polygon(c,PackedVector2Array([Vector2(39,-5),Vector2(46,-2),Vector2(39,1)]),Color("cadce3"))
		"grenade":
			LabSurface.circle(c,Vector2(3,7),15,Color(0,0,0,0.26))
			LabSurface.circle(c,Vector2(0,4),14,Color("376f47"))
			c.draw_arc(Vector2(0,4),13,0,TAU,24,Color("2d6b3e"),2,true)
			for x in [-7,0,7]: LabSurface.line(c,Vector2(x,-6),Vector2(x,14),Color(0.72,0.88,0.7,0.16),1)
			for y in [-2,5,12]: LabSurface.line(c,Vector2(-10,y),Vector2(10,y),Color(0.04,0.12,0.06,0.28),1)
			LabSurface.plate(c,Rect2(-6,-14,12,8),Color("6d7f8c"),2,Color("a8b8c2"))
			LabSurface.line(c,Vector2(4,-14),Vector2(14,-22),AMBER,2)
			c.draw_arc(Vector2(10,-17),7,-1.8,1.0,12,Color("c8d3d6"),2,true)
			LabSurface.circle(c,Vector2(15,-23),2.5,RED)
			c.draw_arc(Vector2(-4,0),6,2.4,4.6,8,Color(1,1,1,0.25),2,true)
		"turret":
			LabSurface.plate(c,Rect2(-20,8,40,12),Color("3a4a55"),3)
			LabSurface.line(c,Vector2(-16,20),Vector2(-22,28),Color("6d7f8c"),3)
			LabSurface.line(c,Vector2(16,20),Vector2(22,28),Color("6d7f8c"),3)
			LabSurface.line(c,Vector2(0,20),Vector2(0,30),Color("6d7f8c"),3)
			LabSurface.plate(c,Rect2(-14,-8,28,20),Color("5c6d78"),4,Color("a8b8c2"))
			LabSurface.plate(c,Rect2(8,-5,26,8),Color("4a5c68"),3)
			LabSurface.circle(c,Vector2(0,-2),5,Color("173039"))
			LabSurface.circle(c,Vector2(0,-2),2.5,color)
			LabSurface.circle(c,Vector2(34,-1),3,AMBER)
		"drone":
			LabSurface.plate(c,Rect2(-14,-6,28,14),Color("5c6d78"),5,Color("a8b8c2"))
			LabSurface.circle(c,Vector2(0,0),5,Color("173039"))
			LabSurface.circle(c,Vector2(0,0),2.5,color)
			for p in [Vector2(-18,-8),Vector2(18,-8),Vector2(-18,8),Vector2(18,8)]:
				LabSurface.circle(c,p,7,Color("3a4a55"))
				c.draw_arc(p,8,0,TAU,16,Color("8aa0ad"),1.5,true)
				LabSurface.line(c,p+Vector2(-6,0),p+Vector2(6,0),color,1)
			LabSurface.line(c,Vector2(-14,0),Vector2(-18,-8),Color("6d7f8c"),2)
			LabSurface.line(c,Vector2(14,0),Vector2(18,-8),Color("6d7f8c"),2)
		"flak":
			LabSurface.plate(c,Rect2(-12,4,16,14),Color("3a4a55"),2)
			LabSurface.plate(c,Rect2(-20,-10,32,18),Color("6d7f8c"),4,Color("a8b8c2"))
			LabSurface.plate(c,Rect2(8,-8,24,12),Color("4a5c68"),3)
			c.draw_arc(Vector2(-6,-16),10,-2.6,-0.4,14,color,3,true)
			LabSurface.circle(c,Vector2(-6,-16),3,AMBER)
			LabSurface.circle(c,Vector2(32,-2),4,color)
			c.draw_arc(Vector2(32,-2),8,-0.8,0.8,8,AMBER,2,true)
		"sword":
			grip(c,Vector2(-32,0),Vector2(-14,0),7)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-15,-10),Vector2(-10,-7),Vector2(-8,0),Vector2(-10,7),Vector2(-15,10)]),Color("91a6b4"))
			blade(c,PackedVector2Array([Vector2(-9,-4),Vector2(24,-4),Vector2(38,0),Vector2(24,4),Vector2(-9,4)]),PackedVector2Array([Vector2(-8,0),Vector2(36,0)]))
			LabSurface.polygon(c,PackedVector2Array([Vector2(-8,0),Vector2(36,0),Vector2(24,4),Vector2(-8,4)]),Color("698493"))
			bolt(c,Vector2(-13,0),2.0,AMBER)
		"axe":
			grip(c,Vector2(-28,2),Vector2(5,0),6,Color("947046"))
			LabSurface.polygon(c,PackedVector2Array([Vector2(3,-5),Vector2(8,-15),Vector2(24,-19),Vector2(31,-13),Vector2(34,1),Vector2(29,16),Vector2(9,11),Vector2(6,4)]),Color("6e8796"))
			blade(c,PackedVector2Array([Vector2(24,-19),Vector2(31,-13),Vector2(34,1),Vector2(29,16),Vector2(23,12),Vector2(27,0),Vector2(24,-10)]),PackedVector2Array([Vector2(29,-12),Vector2(31,1),Vector2(27,13)]))
			LabSurface.plate(c,Rect2(4,-6,10,12),Color("3e5664"),2)
			bolt(c,Vector2(9,0),2.3,AMBER)
		"spear":
			LabSurface.line(c,Vector2(-46,0),Vector2(18,0),Color("8f6742"),5.0)
			grip(c,Vector2(-24,0),Vector2(-5,0),6)
			LabSurface.plate(c,Rect2(10,-4,8,8),Color("77909e"),1)
			blade(c,PackedVector2Array([Vector2(16,-2),Vector2(25,-7),Vector2(48,0),Vector2(25,7),Vector2(16,2)]),PackedVector2Array([Vector2(18,0),Vector2(47,0)]))
			LabSurface.polygon(c,PackedVector2Array([Vector2(18,0),Vector2(47,0),Vector2(25,7)]),Color("7f9caa"))
			LabSurface.plate(c,Rect2(-48,-3,5,6),Color("8aa3b1"),1)
		"hammer":
			grip(c,Vector2(-29,0),Vector2(7,0),7)
			LabSurface.polygon(c,PackedVector2Array([Vector2(5,-12),Vector2(10,-17),Vector2(27,-17),Vector2(32,-11),Vector2(32,11),Vector2(27,17),Vector2(10,17),Vector2(5,12)]),Color("6e8392"))
			LabSurface.plate(c,Rect2(7,-16,5,32),Color("b8cbd4"),2)
			LabSurface.plate(c,Rect2(25,-16,5,32),Color("b8cbd4"),2)
			LabSurface.plate(c,Rect2(14,-9,8,18),Color("3e5363"),2)
			bolt(c,Vector2(18,0),2.6,AMBER)
		"knife":
			grip(c,Vector2(-21,0),Vector2(-7,0),7,Color("3a5157"))
			LabSurface.line(c,Vector2(-6,-7),Vector2(-6,7),Color("b8ccd4"),2.5)
			blade(c,PackedVector2Array([Vector2(-4,-5),Vector2(12,-5),Vector2(25,-2),Vector2(17,4),Vector2(-4,5)]),PackedVector2Array([Vector2(-3,-1),Vector2(22,-2)]))
			LabSurface.polygon(c,PackedVector2Array([Vector2(-3,0),Vector2(22,-2),Vector2(17,4),Vector2(-3,5)]),Color("7797a6"))
		"katana":
			grip(c,Vector2(-37,2),Vector2(-18,1),6,Color("493044"))
			LabSurface.ellipse(c,Vector2(-16,1),Vector2(2.5,8),Color("cba269"))
			blade(c,PackedVector2Array([Vector2(-13,-3),Vector2(5,-3),Vector2(24,-5),Vector2(39,-9),Vector2(36,-3),Vector2(24,0),Vector2(6,3),Vector2(-13,4)]),PackedVector2Array([Vector2(-12,-1),Vector2(5,-1),Vector2(24,-3),Vector2(37,-7)]))
			c.draw_polyline(PackedVector2Array([Vector2(-11,2),Vector2(5,1),Vector2(24,-1),Vector2(35,-4)]),Color("91adb9"),1.0,true)
		"scythe":
			LabSurface.line(c,Vector2(-38,7),Vector2(18,-3),Color("886340"),5)
			grip(c,Vector2(-34,6),Vector2(-17,3),7)
			blade(c,PackedVector2Array([Vector2(10,-4),Vector2(17,-17),Vector2(27,-21),Vector2(39,-15),Vector2(44,-5),Vector2(43,8),Vector2(35,20),Vector2(38,4),Vector2(34,-6),Vector2(25,-10),Vector2(20,-2)]),PackedVector2Array([Vector2(19,-14),Vector2(28,-17),Vector2(38,-12),Vector2(41,-3),Vector2(40,7)]))
			bolt(c,Vector2(17,-4),2.5,AMBER)
		"mace":
			grip(c,Vector2(-28,0),Vector2(4,0),7)
			LabSurface.circle(c,Vector2(17,0),12,Color("637c8e"))
			for i in range(8):
				var axis=Vector2.from_angle(float(i)*TAU/8.0)
				var cross=axis.orthogonal()*3
				LabSurface.polygon(c,PackedVector2Array([Vector2(17,0)+axis*9-cross,Vector2(17,0)+axis*17,Vector2(17,0)+axis*9+cross]),Color("d3e1e5"))
			LabSurface.circle(c,Vector2(17,0),6,Color("8ca6b7"))
			bolt(c,Vector2(17,0),2.3,AMBER)
		"chainsaw":
			LabSurface.plate(c,Rect2(-27,-11,27,25),Color("bd7137"),5,Color("e2aa62"),true)
			c.draw_arc(Vector2(-20,0),13,1.5,4.5,22,Color("9eafba"),3,true)
			LabSurface.plate(c,Rect2(-4,-7,38,14),Color("91aab7"),7,Color("d1e2e9"),true)
			LabSurface.plate(c,Rect2(-1,-4,30,8),Color("465d6b"),4,Color.TRANSPARENT,true)
			for x in range(0,32,6):
				LabSurface.polygon(c,PackedVector2Array([Vector2(x,-7),Vector2(x+3,-11),Vector2(x+5,-7)]),TEXT)
				LabSurface.polygon(c,PackedVector2Array([Vector2(x,7),Vector2(x+3,11),Vector2(x+5,7)]),TEXT)
			vents(c,Rect2(-21,-5,14,8),4)
			bolt(c,Vector2(-7,7),2,AMBER)
		"bat":
			LabSurface.polygon(c,PackedVector2Array([Vector2(-30,-3),Vector2(-13,-3),Vector2(0,-6),Vector2(24,-8),Vector2(31,-5),Vector2(33,0),Vector2(31,5),Vector2(24,8),Vector2(0,6),Vector2(-13,3),Vector2(-30,3)]),Color("bf9256"))
			grip(c,Vector2(-29,0),Vector2(-12,0),6,Color("795537"))
			c.draw_line(Vector2(-2,-3),Vector2(25,-4),Color("f0d4a0"),1.3,true)
			c.draw_line(Vector2(4,2),Vector2(26,1),Color("8d6338"),1,true)
		"whip":
			grip(c,Vector2(-40,0),Vector2(-21,0),6,Color("52443b"))
			var cord=PackedVector2Array()
			for i in range(41):
				var t=float(i)/40.0
				cord.append(Vector2(lerpf(-20,50,t),sin(t*TAU*1.1)*7.0*(1.0-t)))
			c.draw_polyline(cord,Color("c5985b"),2.4,true)
			c.draw_polyline(cord,Color("efd1a0"),0.65,true)
		"plasma_blade":
			grip(c,Vector2(-31,0),Vector2(-13,0),8,Color("3d5465"))
			LabSurface.plate(c,Rect2(-13,-7,8,14),Color("667f90"),2)
			soft_glow(c,Vector2(14,0),25,Color(color.r,color.g,color.b,0.65))
			LabSurface.polygon(c,PackedVector2Array([Vector2(-5,-5),Vector2(25,-5),Vector2(39,0),Vector2(25,5),Vector2(-5,5)]),color)
			c.draw_polyline(PackedVector2Array([Vector2(-3,-2),Vector2(24,-2),Vector2(35,0)]),Color("efffff"),2.3,true)
			bolt(c,Vector2(-9,0),2.1,Color("e5ffff"))
		"crowbar":
			c.draw_polyline(PackedVector2Array([Vector2(-31,10),Vector2(-25,0),Vector2(-18,-3),Vector2(23,-3),Vector2(30,-8),Vector2(34,-5)]),Color("92aab7"),5,true)
			c.draw_polyline(PackedVector2Array([Vector2(-30,8),Vector2(-24,-1),Vector2(-18,-4),Vector2(23,-4),Vector2(30,-9)]),Color("e4eff4"),1.2,true)
			grip(c,Vector2(-12,-3),Vector2(8,-3),6,Color("a34038"))
		"halberd":
			LabSurface.line(c,Vector2(-46,0),Vector2(26,0),Color("8f6d43"),5)
			grip(c,Vector2(-29,0),Vector2(-10,0),6)
			blade(c,PackedVector2Array([Vector2(10,-3),Vector2(16,-14),Vector2(30,-18),Vector2(28,-10),Vector2(36,-6),Vector2(28,-3),Vector2(47,0),Vector2(28,3),Vector2(30,12),Vector2(17,16),Vector2(12,5)]),PackedVector2Array([Vector2(16,-2),Vector2(45,0)]))
			bolt(c,Vector2(20,0),2.5,AMBER)
		"hook":
			grip(c,Vector2(-31,0),Vector2(-8,0),7)
			c.draw_polyline(PackedVector2Array([Vector2(-8,0),Vector2(7,0),Vector2(15,-9),Vector2(25,-10),Vector2(32,-4),Vector2(32,5),Vector2(26,10),Vector2(20,8)]),Color("9eb7c4"),5,true)
			c.draw_polyline(PackedVector2Array([Vector2(-7,-1),Vector2(6,-1),Vector2(14,-10),Vector2(25,-11),Vector2(32,-5)]),Color("eef8fa"),1.2,true)
			LabSurface.polygon(c,PackedVector2Array([Vector2(24,8),Vector2(18,2),Vector2(19,10)]),Color("d7e8ef"))
		"railgun":
			LabSurface.plate(c,Rect2(-28,-6,24,16),Color("3a4a55"),3)
			LabSurface.plate(c,Rect2(-8,-4,40,8),Color("4a5c68"),2)
			LabSurface.line(c,Vector2(-8,-10),Vector2(28,-10),color,2)
			LabSurface.circle(c,Vector2(34,0),3,AMBER)
		"crossbow":
			c.draw_arc(Vector2(6,0),20,-1.2,1.2,14,Color("6a5a48"),4,true)
			LabSurface.plate(c,Rect2(-24,-4,40,8),Color("4a3a32"),2)
			LabSurface.line(c,Vector2(14,0),Vector2(32,0),Color("c5d2d8"),2)
		"rocket_gun":
			LabSurface.plate(c,Rect2(-22,-10,28,22),Color("5c6d78"),4,Color("a8b8c2"))
			LabSurface.plate(c,Rect2(4,-6,28,12),Color("6a5a48"),3,AMBER)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-22,-6),Vector2(-32,0),Vector2(-22,6)]),AMBER)
		"flamer":
			LabSurface.plate(c,Rect2(-18,-8,24,20),Color("3a4a55"),3)
			LabSurface.plate(c,Rect2(4,-5,22,10),Color("4a5c68"),3)
			LabSurface.polygon(c,PackedVector2Array([Vector2(24,-8),Vector2(38,0),Vector2(24,8)]),AMBER)
		"freezer":
			LabSurface.plate(c,Rect2(-20,-8,30,16),Color("4a6a78"),3,Color("74cafa"))
			LabSurface.plate(c,Rect2(8,-4,22,8),Color("8aa0ad"),2)
			LabSurface.circle(c,Vector2(32,0),4,Color("74cafa"))
		"tesla_gun":
			LabSurface.plate(c,Rect2(-18,-8,28,16),Color("3a4a55"),3)
			LabSurface.circle(c,Vector2(18,0),10,Color("4a5c68"))
			c.draw_arc(Vector2(18,0),14,-0.8,0.8,10,color,2,true)
			LabSurface.circle(c,Vector2(18,0),3,AMBER)
		"harpoon":
			LabSurface.plate(c,Rect2(-26,-6,36,12),Color("5c6d78"),3)
			LabSurface.polygon(c,PackedVector2Array([Vector2(8,-6),Vector2(36,0),Vector2(8,6)]),Color("c5d2d8"))
		"glue_gun":
			LabSurface.plate(c,Rect2(-16,2,14,14),Color("3a4a55"),2)
			LabSurface.plate(c,Rect2(-18,-8,28,14),Color("6d7f8c"),3)
			LabSurface.circle(c,Vector2(16,-2),5,Color("e06f72"))
		"bouncer":
			LabSurface.plate(c,Rect2(-20,-8,32,16),Color("6d7f8c"),4)
			LabSurface.circle(c,Vector2(18,0),8,Color("e06f72"))
			c.draw_arc(Vector2(18,0),10,0,TAU,16,AMBER,2,true)
		"cannon":
			LabSurface.plate(c,Rect2(-24,-12,28,24),Color("3a4a55"),4)
			LabSurface.plate(c,Rect2(0,-8,34,16),Color("5c6d78"),4)
			LabSurface.circle(c,Vector2(-10,14),6,Color("4a3a32"))
			LabSurface.circle(c,Vector2(10,14),6,Color("4a3a32"))
		"minigun":
			LabSurface.plate(c,Rect2(-20,-10,22,22),Color("3a4a55"),3)
			for y in [-6,0,6]: LabSurface.plate(c,Rect2(0,y-3,30,6),Color("4a5c68"),2)
		"pulse_gun":
			LabSurface.plate(c,Rect2(-18,-10,30,20),Color("3a4a55"),4)
			LabSurface.circle(c,Vector2(20,0),10,color)
			c.draw_arc(Vector2(20,0),14,0,TAU,16,AMBER,2,true)
		"grapple":
			LabSurface.plate(c,Rect2(-20,-6,28,12),Color("5c6d78"),3)
			c.draw_arc(Vector2(16,4),8,-0.2,3.0,12,AMBER,3,true)
		"mine_gun":
			LabSurface.plate(c,Rect2(-20,-10,32,20),Color("6d7f8c"),4)
			LabSurface.circle(c,Vector2(18,0),8,Color("a56750"))
			LabSurface.circle(c,Vector2(18,0),3,RED)
		"balloon_gun":
			LabSurface.plate(c,Rect2(-18,-6,26,14),Color("6d7f8c"),3)
			LabSurface.circle(c,Vector2(18,-8),10,Color("e06f72"))
			LabSurface.line(c,Vector2(18,2),Vector2(18,12),Color("b4c8cc"),1)
		"vortex":
			LabSurface.plate(c,Rect2(-16,-10,28,20),Color("3a4a55"),4)
			c.draw_arc(Vector2(14,0),12,0,4,16,color,3,true)
			c.draw_arc(Vector2(14,0),7,2,6,12,AMBER,2,true)
		"disc_gun":
			LabSurface.plate(c,Rect2(-20,-8,26,16),Color("5c6d78"),3)
			LabSurface.circle(c,Vector2(16,0),12,Color("3a4a55"))
			c.draw_arc(Vector2(16,0),11,0,TAU,16,AMBER,2,true)
		"taser":
			LabSurface.plate(c,Rect2(-16,-6,22,12),Color("3a4a55"),3)
			LabSurface.line(c,Vector2(6,0),Vector2(22,-6),color,2)
			LabSurface.line(c,Vector2(6,0),Vector2(22,6),color,2)
		"cluster":
			LabSurface.plate(c,Rect2(-20,-8,30,16),Color("5c6d78"),3)
			for p in [Vector2(16,-6),Vector2(22,4),Vector2(12,6)]: LabSurface.circle(c,p,5,Color("3e8a52"))
		"wind_gun":
			LabSurface.plate(c,Rect2(-18,-10,24,22),Color("3a4a55"),4)
			LabSurface.circle(c,Vector2(12,0),12,Color("182731"))
			for i in range(3):
				var a=i*TAU/3.0
				LabSurface.polygon(c,PackedVector2Array([Vector2.from_angle(a)*3+Vector2(12,0),Vector2.from_angle(a+0.4)*12+Vector2(12,0),Vector2.from_angle(a+1)*8+Vector2(12,0)]),color)
		"emp":
			LabSurface.circle(c,Vector2.ZERO,8,color)
			c.draw_arc(Vector2.ZERO,14,0,TAU,24,color,2,true)
			LabSurface.circle(c,Vector2.ZERO,3,TEXT)
		"slug":
			LabSurface.circle(c,Vector2.ZERO,5,color)
			LabSurface.circle(c,Vector2.ZERO,2.5,TEXT)
			LabSurface.circle(c,Vector2(-8,0),3,Color(color.r,color.g,color.b,0.4))
		"rubber":
			bevel_box(c,Rect2(-18,-18,36,36),Color("2f5142"),8,Color("57806a"),2)
			LabSurface.rect(c,Rect2(-12,-12,24,24),Color("3d6752"),false,2)
			if fine:
				for ring in range(3): c.draw_arc(Vector2.ZERO,6.0+float(ring)*4.0,0,TAU,20,Color(1,1,1,0.07),1,true)
			c.draw_arc(Vector2(3,-3),11,3.4,5.2,12,Color(1,1,1,0.4),3,true)
		"ice":
			bevel_box(c,Rect2(-22,-12,44,24),Color("a6ddef"),5,Color("e2f7ff"),2)
			LabSurface.rect(c,Rect2(-17,-8,34,10),Color(1,1,1,0.28))
			if fine:
				LabSurface.line(c,Vector2(-12,7),Vector2(-4,-7),Color(1,1,1,0.55),2,true)
				LabSurface.line(c,Vector2(2,8),Vector2(11,-5),Color(1,1,1,0.4),1.5,true)
			LabSurface.line(c,Vector2(-16,-9),Vector2(14,-9),Color(1,1,1,0.75),2,true)
		"soap":
			bevel_box(c,Rect2(-18,-10,36,20),Color("e0c9ec"),9,Color("bb9dcb"),2)
			c.draw_arc(Vector2.ZERO,8,0,TAU,20,Color(1,1,1,0.30),1.5,true)
			LabSurface.circle(c,Vector2(7,-3),3.5,Color(1,1,1,0.6))
			if fine: c.draw_arc(Vector2(-6,4),4,2.4,4.8,8,Color(1,1,1,0.22),1.5,true)
		"sponge":
			bevel_box(c,Rect2(-20,-16,40,32),Color("e0c25a"),4,Color("f0d888"),2)
			for pore in [Vector2(-11,-7),Vector2(4,3),Vector2(-4,9),Vector2(11,-9),Vector2(-13,5),Vector2(9,9)]:
				LabSurface.recess(c,pore,3.2,Color("b78f36"))
			if fine:
				for tear in range(5): LabSurface.recess(c,Vector2(-15.0+float(tear)*7.0,-11),1.3,Color("bd973b"))
		"anvil":
			LabSurface.polygon(c,PackedVector2Array([Vector2(-23,-13),Vector2(15,-13),Vector2(28,-8),Vector2(18,-3),Vector2(10,-3),Vector2(6,4),Vector2(12,11),Vector2(14,17),Vector2(-22,17),Vector2(-20,11),Vector2(-12,6),Vector2(-11,-3),Vector2(-23,-3)]),Color("718592"))
			LabSurface.plate(c,Rect2(-24,-14,40,5),Color("b3c8d4"),1)
			LabSurface.plate(c,Rect2(-22,13,36,5),Color("455e6e"),1)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-12,-3),Vector2(10,-3),Vector2(6,4),Vector2(12,11),Vector2(-20,11),Vector2(-12,6)]),Color("435a68"))
			LabSurface.recess(c,Vector2(-17,-11),1.5,Color("3d5666"))
		"feather":
			var plume=PackedVector2Array([Vector2(-18,9),Vector2(-14,0),Vector2(-6,-8),Vector2(5,-12),Vector2(19,-12),Vector2(15,-3),Vector2(9,6),Vector2(-3,11)])
			LabSurface.polygon(c,plume,Color("dce9ee"))
			c.draw_line(Vector2(-21,13),Vector2(17,-10),Color("93b2c2"),1.7,true)
			for i in range(7):
				var p=Vector2(-14,8).lerp(Vector2(13,-8),float(i)/6.0)
				c.draw_line(p,p+Vector2(-1,-7),Color("f1fafc"),1,true)
				c.draw_line(p,p+Vector2(7,1),Color("a3c1cf"),0.8,true)
		"spring_block":
			bevel_box(c,Rect2(-22,-9,10,18),Color("647884"),3,Color("9bb0ba"),2)
			bevel_box(c,Rect2(12,-9,10,18),Color("647884"),3,Color("9bb0ba"),2)
			for coil in range(5):
				c.draw_arc(Vector2(-12.0+float(coil)*6.0,0),4.5,PI,TAU,10,color,2.5,true)
				c.draw_arc(Vector2(-9.0+float(coil)*6.0,0),4.5,0,PI,10,color.darkened(0.25),2.5,true)
		"pillow":
			bevel_box(c,Rect2(-22,-14,44,28),Color("ddc9ae"),11,Color("bfa989"),2)
			if fine:
				c.draw_arc(Vector2.ZERO,15,0,TAU,28,Color(1,1,1,0.16),1,true)
				for stitch in range(7): LabSurface.line(c,Vector2(-16.0+float(stitch)*5.4,-11),Vector2(-14.0+float(stitch)*5.4,-11),Color("a8906e"),1.5,true)
			LabSurface.circle(c,Vector2(0,0),3,Color("bfa989"))
		"slime":
			var jelly=PackedVector2Array([Vector2(-22,10),Vector2(-19,1),Vector2(-14,-7),Vector2(-6,-12),Vector2(6,-11),Vector2(14,-6),Vector2(18,2),Vector2(23,10),Vector2(14,14),Vector2(5,12),Vector2(-3,14),Vector2(-12,12)])
			LabSurface.polygon(c,jelly,Color("58d793"))
			LabSurface.ellipse(c,Vector2(-3,-1),Vector2(14,10),Color("76edac"))
			c.draw_arc(Vector2(-4,-2),8,3.4,5.2,24,Color(1,1,1,0.5),2.4,true)
			for p in [Vector2(7,3),Vector2(-9,6),Vector2(2,7)]: c.draw_circle(p,1.8,Color(0.88,1,0.86,0.3),true,-1,true)
		"cork":
			LabSurface.circle(c,Vector2.ZERO,16,Color("b98f57"))
			LabSurface.circle(c,Vector2(-2,-2),13,Color("cfa972"))
			c.draw_arc(Vector2.ZERO,15.5,0,TAU,24,Color("8f6c3c"),2,true)
			if fine:
				for fleck in [Vector2(-5,3),Vector2(4,-5),Vector2(7,5),Vector2(-8,-6),Vector2(1,8)]: LabSurface.circle(c,fleck,1.4,Color("9a7644"))
		"brick":
			bevel_box(c,Rect2(-22,-12,44,24),Color("b05744"),3,Color("d2775f"),2)
			LabSurface.line(c,Vector2(-22,0),Vector2(22,0),Color("7f3a2c"),2.5,true)
			LabSurface.line(c,Vector2(-4,-12),Vector2(-4,0),Color("7f3a2c"),2.5,true)
			LabSurface.line(c,Vector2(8,0),Vector2(8,12),Color("7f3a2c"),2.5,true)
			if fine:
				for grit in [Vector2(-15,-6),Vector2(3,-7),Vector2(-10,6),Vector2(14,5)]: LabSurface.circle(c,grit,1.2,Color(1,1,1,0.12))
		"crystal":
			LabSurface.polygon(c,PackedVector2Array([Vector2(0,-20),Vector2(12,4),Vector2(0,18),Vector2(-12,4)]),Color("74c7e2"))
			LabSurface.polygon(c,PackedVector2Array([Vector2(0,-20),Vector2(12,4),Vector2(0,10)]),Color("a8ecff"))
			LabSurface.polygon(c,PackedVector2Array([Vector2(0,-20),Vector2(-12,4),Vector2(0,10)]),Color("5fb2d0"))
			if fine: LabSurface.line(c,Vector2(0,-18),Vector2(0,16),Color(1,1,1,0.35),1.5,true)
			soft_glow(c,Vector2.ZERO,16,Color(0.6,0.9,1.0,0.35),0.6)
		"tire":
			LabSurface.circle(c,Vector2.ZERO,18,Color("1c262d"))
			LabSurface.circle(c,Vector2.ZERO,15,Color("2b3840"))
			if fine:
				for tread in range(10):
					LabSurface.line(c,Vector2.from_angle(float(tread)*TAU/10.0)*15.0,Vector2.from_angle(float(tread)*TAU/10.0)*18.5,Color("161f25"),3,true)
			LabSurface.circle(c,Vector2.ZERO,8,Color("7a8d98"))
			LabSurface.circle(c,Vector2.ZERO,4,Color("46565f"))
			c.draw_arc(Vector2(-3,-3),12,3.5,5.0,10,Color(1,1,1,0.14),2,true)
		"gyro":
			LabSurface.circle(c,Vector2.ZERO,16,Color("5c6d78"))
			c.draw_arc(Vector2.ZERO,16,0,TAU,24,AMBER,3,true)
			LabSurface.circle(c,Vector2.ZERO,9,Color("8399a2"))
			LabSurface.circle(c,Vector2.ZERO,4,Color("2c3a42"))
			LabSurface.line(c,Vector2(0,-16),Vector2(0,-22),Color("93a7b1"),2,true)
			if fine:
				for spoke in range(6): LabSurface.line(c,Vector2.from_angle(float(spoke)*TAU/6.0)*5.0,Vector2.from_angle(float(spoke)*TAU/6.0)*15.0,Color(0,0,0,0.18),1.5,true)
		"dice":
			bevel_box(c,Rect2(-14,-14,28,28),Color("edf1f4"),6,Color("b9c6cc"),2)
			for pip in [Vector2(-7,-7),Vector2(7,-7),Vector2(0,0),Vector2(-7,7),Vector2(7,7)]:
				LabSurface.circle(c,pip,2.8,Color("28333a"))
				if fine: LabSurface.circle(c,pip+Vector2(-0.7,-0.7),1.1,Color("4a5a63"))
		"sandbag":
			bevel_box(c,Rect2(-20,-13,40,28),Color("9b714a"),11,Color("bb8f63"),2)
			LabSurface.line(c,Vector2(-18,2),Vector2(18,2),Color("7b573a"),2,true)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-6,-13),Vector2(6,-13),Vector2(3,-21),Vector2(-3,-21)]),Color("8a6342"))
			LabSurface.line(c,Vector2(-6,-15),Vector2(6,-15),Color("54402c"),3,true)
			if fine: c.draw_arc(Vector2(-8,-4),7,3.2,4.6,8,Color(1,1,1,0.12),2,true)
		"gel":
			LabSurface.circle(c,Vector2.ZERO,16,Color("49c9a4"))
			LabSurface.circle(c,Vector2(0,-1),13,Color("7cf0c8"))
			soft_glow(c,Vector2.ZERO,16,Color(0.49,0.94,0.78,0.4),0.7)
			LabSurface.circle(c,Vector2(-5,-5),4.5,Color(1,1,1,0.5))
			if fine: c.draw_arc(Vector2.ZERO,12,0.6,2.0,8,Color(1,1,1,0.2),2,true)
		"lead":
			bevel_box(c,Rect2(-16,-16,32,32),Color("434e59"),3,Color("7a8b96"),2)
			LabSurface.rect(c,Rect2(-11,-11,22,22),Color("515f6a"))
			c.draw_string(ThemeDB.fallback_font,Vector2(-9,5),"Pb",HORIZONTAL_ALIGNMENT_CENTER,20,13,Color("cfdde2"))
			if fine:
				for nick in [Vector2(-13,9),Vector2(12,-12)]: LabSurface.circle(c,nick,1.6,Color(0,0,0,0.25))
		"paper":
			bevel_box(c,Rect2(-22,-8,44,16),Color("f2f5f7"),2,Color("c9d5da"),2)
			LabSurface.line(c,Vector2(-22,-1),Vector2(22,-1),Color("d5e0e4"),1,true)
			if fine:
				for rule in range(3): LabSurface.line(c,Vector2(-16,-4.0+float(rule)*4.0),Vector2(13,-4.0+float(rule)*4.0),Color("b7c7cd"),1,true)
		"honeycomb":
			for cell in [Vector2(0,-11),Vector2(-11,6),Vector2(11,6),Vector2(0,4)]:
				LabSurface.polygon(c,_hex(cell,9.0),Color("e0c25a"))
				c.draw_polyline(_hex(cell,9.0)+PackedVector2Array([_hex(cell,9.0)[0]]),Color("a8812c"),1.5,true)
				if fine: LabSurface.polygon(c,_hex(cell,5.0),Color("caa845"))
		"conveyor":
			bevel_box(c,Rect2(-28,-8,56,16),Color("333f48"),4,Color("6b7d88"),2)
			LabSurface.rect(c,Rect2(-26,-6,52,5),Color("1d262c"))
			for roller in [-20,-7,6,19]:
				LabSurface.circle(c,Vector2(roller,3),4,Color("6b7d88"))
				LabSurface.circle(c,Vector2(roller,3),2,Color("2c3841"))
			for chev in [-16,-2,12]:
				c.draw_polyline(PackedVector2Array([Vector2(chev,-6),Vector2(chev+5,-3.5),Vector2(chev,-1)]),color,2,true)
		"spinner_pad":
			LabSurface.circle(c,Vector2.ZERO,18,Color("2f3b44"))
			LabSurface.circle(c,Vector2.ZERO,15,Color("41505a"))
			for vane in range(6):
				LabSurface.polygon(c,PackedVector2Array([Vector2.ZERO,Vector2.from_angle(float(vane)*TAU/6.0)*15.0,Vector2.from_angle(float(vane)*TAU/6.0+0.5)*15.0]),color if vane%2==0 else Color("55666f"))
			LabSurface.circle(c,Vector2.ZERO,5,Color("1d262c"))
			c.draw_arc(Vector2.ZERO,11,0.4,3.6,16,color,2.5,true)
		"updraft":
			bevel_box(c,Rect2(-16,-16,32,32),Color("333f48"),4,Color("6b7d88"),2)
			LabSurface.rect(c,Rect2(-12,-12,24,24),Color("1b232a"))
			for louvre in range(4): LabSurface.line(c,Vector2(-11,-9.0+float(louvre)*7.0),Vector2(11,-9.0+float(louvre)*7.0),Color("42525c"),2,true)
			for shaft in [-6,0,6]:
				LabSurface.line(c,Vector2(shaft,11),Vector2(shaft,-9),color,2,true)
				c.draw_polyline(PackedVector2Array([Vector2(shaft-3,-5),Vector2(shaft,-10),Vector2(shaft+3,-5)]),color,2,true)
		"chiller":
			bevel_box(c,Rect2(-20,-14,40,28),Color("3d5a66"),4,Color("74cafa"),2)
			for fin in range(5): LabSurface.line(c,Vector2(-14.0+float(fin)*7.0,-11),Vector2(-14.0+float(fin)*7.0,11),Color("6fa8bd"),2,true)
			LabSurface.circle(c,Vector2.ZERO,7,Color("1f3742"))
			for spike in range(6): LabSurface.line(c,Vector2.from_angle(float(spike)*TAU/6.0)*2.0,Vector2.from_angle(float(spike)*TAU/6.0)*6.5,Color("d6f4ff"),1.5,true)
			soft_glow(c,Vector2.ZERO,14,Color(0.45,0.79,0.98,0.4),0.6)
		"vacuum_box":
			bevel_box(c,Rect2(-20,-16,40,32),Color("333f48"),4,Color("6b7d88"),2)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-15,-12),Vector2(15,-12),Vector2(7,6),Vector2(-7,6)]),Color("161d23"))
			for suck in range(4):
				c.draw_polyline(PackedVector2Array([Vector2(-12.0+float(suck)*8.0,-10),Vector2(-9.0+float(suck)*8.0,-3),Vector2(-12.0+float(suck)*8.0,4)]),color,1.5,true)
			LabSurface.rect(c,Rect2(-8,7,16,7),Color("4b5b66"))
		"shaker":
			bevel_box(c,Rect2(-16,-14,32,26),Color("647884"),4,Color("9bb0ba"),2)
			LabSurface.rect(c,Rect2(-11,-9,22,7),Color("2c3841"))
			for leg in [-10,10]: c.draw_polyline(PackedVector2Array([Vector2(leg,12),Vector2(leg-4,15),Vector2(leg+4,18),Vector2(leg,21)]),Color("8399a2"),2,true)
			for buzz in [-22,22]: LabSurface.line(c,Vector2(buzz,-6),Vector2(buzz,6),Color(color.r,color.g,color.b,0.5),2,true)
			LabSurface.line(c,Vector2(-7,3),Vector2(7,3),AMBER,2.5,true)
		"pulsar":
			LabSurface.circle(c,Vector2.ZERO,18,Color("2b3740"))
			for wave in range(3): c.draw_arc(Vector2.ZERO,7.0+float(wave)*5.0,0,TAU,26,Color(color.r,color.g,color.b,0.8-0.2*float(wave)),2,true)
			LabSurface.circle(c,Vector2.ZERO,5,color)
			soft_glow(c,Vector2.ZERO,18,Color(color.r,color.g,color.b,0.45),0.7)
		"lift":
			bevel_box(c,Rect2(-26,-9,52,12),Color("5c6d78"),3,Color("93a7b1"),2)
			for post in [-16,0,16]:
				LabSurface.rect(c,Rect2(post-3,2,6,6),Color("3a4a55"))
				LabSurface.rect(c,Rect2(post-4,8,8,2),Color("6b7d88"))
			c.draw_polyline(PackedVector2Array([Vector2(-5,-13),Vector2(0,-19),Vector2(5,-13)]),color,2.5,true)
		"speaker":
			bevel_box(c,Rect2(-14,-16,28,32),Color("2f3b44"),4,Color("6b7d88"),2)
			LabSurface.circle(c,Vector2(0,-4),8,Color("182026"))
			LabSurface.circle(c,Vector2(0,-4),4,Color("55666f"))
			LabSurface.circle(c,Vector2(0,9),4,Color("182026"))
			for ring in range(3): c.draw_arc(Vector2(14,-2),6.0+float(ring)*5.0,-0.9,0.9,10,Color(color.r,color.g,color.b,0.75-0.2*float(ring)),2,true)
		"grav_well":
			LabSurface.circle(c,Vector2.ZERO,18,Color("171d26"))
			for turn in range(4): c.draw_arc(Vector2.ZERO,5.0+float(turn)*4.0,float(turn)*0.9,float(turn)*0.9+3.6,18,Color(0.70,0.47,0.91,0.85-0.15*float(turn)),2,true)
			LabSurface.circle(c,Vector2.ZERO,3.5,Color("d3b6ff"))
			soft_glow(c,Vector2.ZERO,20,Color(0.55,0.33,0.85,0.5),0.8)
		"hover_pad":
			bevel_box(c,Rect2(-26,-7,52,12),Color("3a4a55"),4,Color("8399a2"),2)
			LabSurface.rect(c,Rect2(-22,-5,44,3),Color(color.r,color.g,color.b,0.8))
			for jet in [-16,0,16]:
				LabSurface.polygon(c,PackedVector2Array([Vector2(jet-4,0),Vector2(jet+4,0),Vector2(jet,7)]),Color(color.r,color.g,color.b,0.35))
			soft_glow(c,Vector2(0,4),20,Color(color.r,color.g,color.b,0.35),0.7)
		"zapper":
			LabSurface.circle(c,Vector2.ZERO,17,Color("333f48"))
			LabSurface.circle(c,Vector2.ZERO,13,Color("1c242b"))
			for band in range(3): c.draw_arc(Vector2.ZERO,13.0-float(band)*4.0,0,TAU,20,Color("55666f"),2,true)
			c.draw_polyline(PackedVector2Array([Vector2(-6,-9),Vector2(2,-2),Vector2(-2,1),Vector2(6,9)]),AMBER,2.5,true)
			soft_glow(c,Vector2.ZERO,16,Color(1.0,0.74,0.44,0.4),0.7)
		"metronome":
			LabSurface.polygon(c,PackedVector2Array([Vector2(-13,17),Vector2(13,17),Vector2(0,-19)]),Color("5a4a38"))
			LabSurface.polygon(c,PackedVector2Array([Vector2(-9,15),Vector2(9,15),Vector2(0,-13)]),Color("6d5a44"))
			LabSurface.rect(c,Rect2(-4,-2,8,15),Color("2a2219"))
			if fine:
				for tick in range(4): LabSurface.line(c,Vector2(-3,0.0+float(tick)*3.4),Vector2(3,0.0+float(tick)*3.4),Color("b79a6c"),1,true)
			LabSurface.line(c,Vector2(0,13),Vector2(8,-11),color,2.5,true)
			LabSurface.circle(c,Vector2(6,-4),3.5,AMBER)
		"pump":
			bevel_box(c,Rect2(-15,-6,30,22),Color("55666f"),4,Color("93a7b1"),2)
			LabSurface.rect(c,Rect2(-7,-19,14,14),Color("39474f"))
			LabSurface.rect(c,Rect2(-9,-21,18,4),Color("7a8d98"))
			c.draw_polyline(PackedVector2Array([Vector2(-4,-9),Vector2(0,-15),Vector2(4,-9)]),color,2.5,true)
			LabSurface.circle(c,Vector2(10,5),3,AMBER)
		"scatter_pad":
			bevel_box(c,Rect2(-24,-8,48,16),Color("3a4a55"),4,Color("8399a2"),2)
			for fan in [-0.85,-0.3,0.3,0.85]:
				LabSurface.line(c,Vector2(0,-6),Vector2(0,-6)+Vector2.from_angle(-PI/2+fan)*15.0,AMBER,2,true)
				LabSurface.circle(c,Vector2(0,-6)+Vector2.from_angle(-PI/2+fan)*15.0,2,AMBER)
		"slow_field":
			LabSurface.circle(c,Vector2.ZERO,18,Color("2f3b44"))
			c.draw_arc(Vector2.ZERO,14,0,TAU,26,Color(color.r,color.g,color.b,0.6),2,true)
			LabSurface.rect(c,Rect2(-9,-4,7,8),color)
			LabSurface.rect(c,Rect2(2,-4,7,8),color)
			if fine:
				for drag in range(3): LabSurface.line(c,Vector2(-16.0+float(drag)*2.0,-11),Vector2(-13.0+float(drag)*2.0,-8),Color(1,1,1,0.18),1.5,true)
		"boost_pad":
			bevel_box(c,Rect2(-26,-8,52,16),Color("39474f"),4,Color("8399a2"),2)
			for chev in [-16,-4,8]:
				c.draw_polyline(PackedVector2Array([Vector2(chev,-5),Vector2(chev+8,0),Vector2(chev,5)]),AMBER,2.5,true)
			LabSurface.rect(c,Rect2(-24,-7,3,14),Color(color.r,color.g,color.b,0.7))
		"rotator":
			LabSurface.circle(c,Vector2.ZERO,18,Color("4b5b66"))
			LabSurface.circle(c,Vector2.ZERO,14,Color("2c3841"))
			for blade in range(4):
				LabSurface.line(c,Vector2.ZERO,Vector2.from_angle(float(blade)*TAU/4.0+0.4)*14.0,color,3,true)
				LabSurface.circle(c,Vector2.from_angle(float(blade)*TAU/4.0+0.4)*14.0,2.5,color)
			LabSurface.circle(c,Vector2.ZERO,4,Color("93a7b1"))
		"magnet_pad":
			bevel_box(c,Rect2(-24,-8,48,16),Color("39474f"),4,Color("8399a2"),2)
			LabSurface.rect(c,Rect2(-18,-6,14,12),RED)
			LabSurface.rect(c,Rect2(4,-6,14,12),Color("5da8ff"))
			if fine:
				c.draw_string(ThemeDB.fallback_font,Vector2(-15,4),"N",HORIZONTAL_ALIGNMENT_CENTER,10,10,Color("120b0b"))
				c.draw_string(ThemeDB.fallback_font,Vector2(7,4),"S",HORIZONTAL_ALIGNMENT_CENTER,10,10,Color("0b1220"))
		"thump":
			bevel_box(c,Rect2(-22,-4,44,14),Color("55666f"),3,Color("93a7b1"),2)
			LabSurface.rect(c,Rect2(-12,-12,24,8),Color("39474f"))
			c.draw_polyline(PackedVector2Array([Vector2(-7,-16),Vector2(0,-22),Vector2(7,-16)]),AMBER,3,true)
			for jolt in [-17,17]: LabSurface.line(c,Vector2(jolt,-12),Vector2(jolt,-18),Color(color.r,color.g,color.b,0.6),2,true)
		"grab":
			c.draw_arc(Vector2.ZERO,14,-0.6,4.2,24,color,2,true)
			LabSurface.line(c,Vector2(-5,4),Vector2(4,-5),color,2,true)
			LabSurface.line(c,Vector2(4,-5),Vector2(5,3),color,2,true)
			LabSurface.line(c,Vector2(4,-5),Vector2(-4,-5),color,2,true)
		"pulse":
			LabSurface.circle(c,Vector2.ZERO,4,color)
			c.draw_arc(Vector2.ZERO,12,0,TAU,32,color,1.5,true)
			for p in [Vector2.UP,Vector2.DOWN,Vector2.LEFT,Vector2.RIGHT]: LabSurface.line(c,p*17,p*23,color,2)
		"blast":
			var points = PackedVector2Array()
			for i in range(16): points.append(Vector2.from_angle(i*TAU/16)*(21 if i%2==0 else 10))
			c.draw_polyline(points+PackedVector2Array([points[0]]),color,2,true)
		"freeze":
			for i in range(6):
				var a = Vector2.from_angle(i*TAU/6)
				LabSurface.line(c,Vector2.ZERO,a*20,color,2,true)
				LabSurface.line(c,a*12,a*15+a.orthogonal()*5,color,2,true)
				LabSurface.line(c,a*12,a*15-a.orthogonal()*5,color,2,true)
		"water_pool":
			LabSurface.rect(c,Rect2(-22,-4,44,22),Color(0.29,0.66,0.88,0.5))
			var wv := PackedVector2Array()
			for i in range(13):
				var x = lerp(-22.0,22.0,float(i)/12.0)
				wv.append(Vector2(x,-4+sin(float(i)*0.9)*2.6))
			c.draw_polyline(wv,Color("7fd0f0"),2.0,true)
			LabSurface.rect(c,Rect2(-22,-4,44,22),Color("4aa8e0"),false,1.6)
			LabSurface.circle(c,Vector2(-8,6),2.4,Color(1,1,1,0.35))
			LabSurface.circle(c,Vector2(7,10),1.6,Color(1,1,1,0.25))
		"oil_pool":
			LabSurface.rect(c,Rect2(-22,-2,44,20),Color(0.17,0.18,0.21,0.72))
			LabSurface.rect(c,Rect2(-22,-2,44,20),Color("5b6472"),false,1.6)
			LabSurface.line(c,Vector2(-18,2),Vector2(-4,2),Color(0.75,0.62,0.35,0.55),2,true)
			LabSurface.line(c,Vector2(2,7),Vector2(16,7),Color(0.55,0.72,0.68,0.45),2,true)
			LabSurface.circle(c,Vector2(10,13),2.0,Color(0.8,0.7,0.4,0.35))
		"acid_pool":
			LabSurface.rect(c,Rect2(-22,-2,44,20),Color(0.29,0.87,0.5,0.42))
			LabSurface.rect(c,Rect2(-22,-2,44,20),Color("4ade80"),false,1.6)
			for p in [Vector2(-12,8),Vector2(0,12),Vector2(11,6)]:
				LabSurface.circle(c,p,2.6,Color(0.8,1.0,0.6,0.7))
			LabSurface.line(c,Vector2(-20,-2),Vector2(20,-2),Color("9cf5bf"),2,true)
		"gas_can":
			bevel_box(c,Rect2(-17,-23,34,46),Color("c0503c"),5,Color("f08a63"),3)
			LabSurface.plate(c,Rect2(-11,-17,22,16),Color("8d3527"),3,Color("e07a55"))
			LabSurface.line(c,Vector2(-7,-9),Vector2(7,-9),Color("ffd9a8"),2,true)
			LabSurface.line(c,Vector2(0,-14),Vector2(0,-4),Color("ffd9a8"),2,true)
			LabSurface.plate(c,Rect2(-6,-28,12,6),Color("6f2a1f"),2)
			LabSurface.line(c,Vector2(9,-26),Vector2(16,-14),Color("8a3b2c"),4,true)
			for y in [4,12]: LabSurface.line(c,Vector2(-14,y),Vector2(14,y),Color(0,0,0,0.18),3)
		"battery":
			bevel_box(c,Rect2(-23,-15,46,30),Color("2f3d47"),4,Color("6f8b98"),3)
			LabSurface.plate(c,Rect2(-19,-11,16,22),Color("1a2730"),2,Color("54707d"))
			LabSurface.plate(c,Rect2(3,-11,16,22),Color("1a2730"),2,Color("54707d"))
			LabSurface.line(c,Vector2(-11,-4),Vector2(-11,4),Color("ffd97a"),2.4,true)
			LabSurface.line(c,Vector2(-15,0),Vector2(-7,0),Color("ffd97a"),2.4,true)
			LabSurface.line(c,Vector2(7,0),Vector2(15,0),Color("9fe8ff"),2.4,true)
			LabSurface.rect(c,Rect2(-26,-6,3,12),Color("cfd9de"))
			LabSurface.rect(c,Rect2(23,-6,3,12),Color("cfd9de"))
		"cable":
			LabSurface.line(c,Vector2(-24,0),Vector2(24,0),Color("1d2730"),7,true)
			var cw := PackedVector2Array()
			for i in range(17):
				var x = lerp(-22.0,22.0,float(i)/16.0)
				cw.append(Vector2(x,sin(float(i)*0.85)*3.4))
			c.draw_polyline(cw,Color("d8a74f"),2.6,true)
			for x in [-24.0,24.0]:
				LabSurface.rect(c,Rect2(x-3,-5,6,10),Color("cfd9de"))
				bolt(c,Vector2(x,0),1.4,Color("9fe8ff"))
		"firework":
			bevel_box(c,Rect2(-9,-20,18,34),Color("b8465f"),3,Color("f08aa4"),2)
			LabSurface.polygon(c,PackedVector2Array([Vector2(-9,-20),Vector2(0,-31),Vector2(9,-20)]),Color("ffd97a"))
			for y in [-12,-4,4]: LabSurface.line(c,Vector2(-8,y),Vector2(8,y),Color(1,1,1,0.3),1.6)
			LabSurface.line(c,Vector2(0,14),Vector2(0,22),Color("8a6a3a"),2,true)
			LabSurface.circle(c,Vector2(0,23),2.2,AMBER)
			soft_glow(c,Vector2(0,23),7,Color(1.0,0.7,0.3,0.8),0.9)
		"torch":
			LabSurface.line(c,Vector2(-24,8),Vector2(10,-6),Color("6b4a2c"),7,true)
			LabSurface.line(c,Vector2(-24,8),Vector2(10,-6),Color("8d6238"),3,true)
			LabSurface.plate(c,Rect2(6,-14,12,14),Color("3a3026"),3,Color("6b5a44"))
			soft_glow(c,Vector2(14,-13),13,Color(1.0,0.6,0.2,0.9),1.2)
			LabSurface.polygon(c,PackedVector2Array([Vector2(8,-13),Vector2(14,-30),Vector2(20,-13)]),Color("ff8a33"))
			LabSurface.polygon(c,PackedVector2Array([Vector2(11,-13),Vector2(14,-24),Vector2(17,-13)]),Color("ffe6a8"))
		"extinguisher":
			bevel_box(c,Rect2(-13,-22,26,44),Color("c0392b"),8,Color("ef7361"),3)
			LabSurface.plate(c,Rect2(-9,-14,18,26),Color(1,1,1,0.12),4)
			LabSurface.plate(c,Rect2(-6,-28,12,7),Color("46525c"),2,Color("7e939e"))
			LabSurface.line(c,Vector2(2,-26),Vector2(15,-20),Color("3d4750"),4,true)
			LabSurface.circle(c,Vector2(17,-19),3.4,Color("8d9ba5"))
			LabSurface.line(c,Vector2(-11,4),Vector2(11,4),Color("f6c453"),2,true)
			LabSurface.circle(c,Vector2(0,12),4.0,Color(1,1,1,0.22))
		"link":
			c.draw_arc(Vector2(-7,6),10,0,TAU,24,color,2,true)
			c.draw_arc(Vector2(7,-6),10,0,TAU,24,color,2,true)
		"delete":
			LabSurface.line(c,Vector2(-15,-11),Vector2(15,-11),color,2)
			LabSurface.rect(c,Rect2(-11,-7,22,24),color,false,2)
			LabSurface.line(c,Vector2(-5,-17),Vector2(5,-17),color,2)
			for x in [-4,4]: LabSurface.line(c,Vector2(x,-2),Vector2(x,11),color,2)
		"clear_scene", "clear":
			LabSurface.line(c,Vector2(12,-13), Vector2(-3,3), color, 2.4, true)
			LabSurface.line(c,Vector2(-6,0), Vector2(0,6), color, 2.0, true)
			c.draw_polyline(PackedVector2Array([
				Vector2(-6,0), Vector2(-15,8), Vector2(-13,15),
				Vector2(-7,15), Vector2(0,6)
			]), color, 1.8, true)
			LabSurface.line(c,Vector2(-3,3), Vector2(-10,12), color, 1.4, true)
			LabSurface.line(c,Vector2(5,6), Vector2(13,6), color, 1.5, true)
			LabSurface.line(c,Vector2(9,2), Vector2(9,10), color, 1.5, true)
			LabSurface.line(c,Vector2(-5,-9), Vector2(-1,-9), color, 1.2, true)
			LabSurface.line(c,Vector2(-3,-11), Vector2(-3,-7), color, 1.2, true)
		"pan":
			for v in [Vector2.UP,Vector2.DOWN,Vector2.LEFT,Vector2.RIGHT]:
				LabSurface.line(c,Vector2.ZERO,v*18,color,2)
				LabSurface.line(c,v*18,v*12+v.orthogonal()*5,color,2)
				LabSurface.line(c,v*18,v*12-v.orthogonal()*5,color,2)
	weapon_finish(c,kind,color)
	c.draw_set_transform(Vector2.ZERO)
